Comment out Emacs for now.

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -29,10 +29,10 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           python -m pip install tox coverage
-      - name: Set up Emacs
-        uses: purcell/setup-emacs@v3.0
-        with:
-          version: 24.4
+#      - name: Set up Emacs
+#        uses: purcell/setup-emacs@v3.0
+#        with:
+#          version: 24.4
       - name: Set up Node
         uses: actions/setup-node@v2
         with:
@@ -46,18 +46,18 @@ jobs:
         run: |
           if [[ $PYTHON == '2.7' ]]; then python test/PySrc/tests/validate_legacy_python.py && exit || exit 1 ; fi
           python -m tox -e py
-      - name: Test with Emacs
-        id: emacs-tests
-        continue-on-error: true
-        run: |
-          emacs -Q --batch -L emacs-live-py-mode --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile emacs-live-py-mode/*.el
-          # Fake a tty with the script command.
-          script -e -temacs-timing -c "emacs -Q -nw -L emacs-live-py-mode -L plugin/PySrc -l live-py-mode.el -l live-py-test.el -f ert-run-tests-batch-and-exit"
-      - name: Display Emacs Test Results
-        if: ${{ steps.emacs-tests.outcome == 'failure' }}
-        run: |
-          scriptreplay emacs-timing
-          exit 1
+#      - name: Test with Emacs
+#        id: emacs-tests
+#        continue-on-error: true
+#        run: |
+#          emacs -Q --batch -L emacs-live-py-mode --eval '(setq byte-compile-error-on-warn t)' -f batch-byte-compile emacs-live-py-mode/*.el
+#          # Fake a tty with the script command.
+#          script -e -temacs-timing -c "emacs -Q -nw -L emacs-live-py-mode -L plugin/PySrc -l live-py-mode.el -l live-py-test.el -f ert-run-tests-batch-and-exit"
+#      - name: Display Emacs Test Results
+#        if: ${{ steps.emacs-tests.outcome == 'failure' }}
+#        run: |
+#          scriptreplay emacs-timing
+#          exit 1
       - name: Test JavaScript
         run: |
           cd html
